name: SonarCloud Analysis for Vulnerable Test Repos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - name: DVWA
            path: VulnerableTestRepos/DVWA
          - name: NodeGoat
            path: VulnerableTestRepos/NodeGoat
          - name: VulnerableApp
            path: VulnerableTestRepos/VulnerableApp
          - name: WebGoat
            path: VulnerableTestRepos/WebGoat
          - name: juice-shop
            path: VulnerableTestRepos/juice-shop

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Java environment for Java projects
      - name: Set up Java
        if: matrix.project.name == 'VulnerableApp' || matrix.project.name == 'Webgoat'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

            # Build step for Java projects (Maven or Gradle)
      - name: Build Java Project with Maven
        if: matrix.project.name == 'Webgoat'
        run: |
         cd ${{ matrix.project.path }}
         mvn clean compile

      - name: Build Java Project with Gradle
        if: matrix.project.name == 'VulnerableApp'
        run: |
          cd ${{ matrix.project.path }}
          ./gradlew build

      # Build step for Java projects
      - name: Build Java Project
        if: matrix.project.name == 'VulnerableApp' || matrix.project.name == 'Webgoat'
        run: |
          cd ${{ matrix.project.path }}
          mvn clean compile

      - name: Analyze Project with SonarCloud
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Running SonarCloud analysis for ${{ matrix.project.name }}"
          docker run --rm \
          -e SONAR_HOST_URL=$SONAR_HOST_URL \
          -e SONAR_TOKEN=$SONAR_TOKEN \
          -v "${{ github.workspace }}/${{ matrix.project.path }}:/usr/src" \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=${{ matrix.project.name }} \
          -Dsonar.organization=sast-pipeline \
          -Dsonar.sources=/usr/src
